from backend.gpt_messaging.gpt import run_get_gpt_results, send_messages
import timeit 

if __name__ == "__main__":
    qs = ["What is the highest level of eduation the applicant has achieved?", "Is the applicant proficient with any languages other than English?"]
    args = {'resume_info': ('HR  Manager,  Global  Enterprises  March  2018  –  Present  ●  Developed  and  executed  HR  strategies  aligned  with  business  objectives,  resulting  in  a  20%  increase in employee retention. ●  Managed  end-to-end  recruitment  processes,  successfully  filling  over  100  positions  annually.  ●  Addressed  employee  grievances  and  implemented  conflict  resolution  strategies,  improving  workplace satisfaction by 15%. ●  Led  performance  management  initiatives,  including  annual  appraisals  and  development  plans.  ●  Ensured  compliance  with  labor  laws  and  company  policies,  reducing  legal  disputes  by  10%.  ,HR  Generalist,  Tech  Solutions  Inc.  June  2015  –  February  2018  ●  Assisted  in  the  recruitment  and  onboarding  of  new  employees,  enhancing  the  onboarding  process efficiency by 25%. ●  Managed  employee  benefits  programs,  achieving  a  95%  satisfaction  rate  among  staff.  ●  Conducted  training  sessions  on  company  policies  and  professional  development.  ●  Supported  performance  management  processes,  including  feedback  and  coaching.  ', ',  M.A.  in  Human  Resources  Management  University  of  Tokyo,  2013–2015  ,  B.A.  in  Business  Administration  Keio  University,  2009–2013 ', '●  Safety  and  Health  Promotion  Officer  (2008)  ●  HR  Software:  PeopleSoft,  SAP  (Advanced)  ●  English:  TOEIC  Score  780  (2008)  ●  Computer:  Microsoft  Word,  Excel,  PowerPoint  (Advanced)  \n ', '●  HR  Management:  Talent  Acquisition,  Employee  Relations,  Performance  Management  ●  HR  Systems:  Workday,  ADP,  BambooHR  ●  Legal  Compliance:  Labor  Laws,  Employment  Regulations  ●  Communication:  Negotiation,  Conflict  Resolution,  Presentation  ●  Leadership:  Team  Building,  Staff  Development,  Strategic  Planning  ●  Other:  Microsoft  Office  Suite,  Data  Analysis  '), 
            'interview_info': (['', '  Extensive  experience  in  HR  management,  with  a  focus  on  talent  acquisition  and  employee  \nrelations.\n ', '  Proficient  in  HR  systems  such  as  Workday  and  ADP.  ', '  Strong  understanding  of  labor  laws  and  HR  best  practices.  ', '  Excellent  communication  and  leadership  skills.  ', '  Proven  track  record  in  developing  and  implementing  HR  strategies  that  align  with  business  \nobjectives.\n'], [], "Taro  is  a  strong  candidate  for  the  HR  Manager  position,  bringing  a  wealth  of  experience  in  HR  management and a solid understanding of HR systems and legal compliance. His skills align well with the requirements of the role, particularly in talent acquisition and employee relations. He  would  be  a  valuable  addition  to  the  team,  with  a  short  learning  curve  to  adapt  to  the  company's  specific HR tools and international practices.  "), 
            'requirements': ['', '  Proven  working  experience  as  HR  Manager  or  other  HR  Executive.  ', '  People-oriented  and  results-driven.  ', '  Demonstrable  experience  with  Human  Resources  metrics.  ', '  Knowledge  of  HR  systems  and  databases.  ', '  Ability  to  architect  strategy  along  with  leadership  skills.  ', '  Excellent  active  listening,  negotiation,  and  presentation  skills.  ', '  Competence  to  build  and  effectively  manage  interpersonal  relationships  at  all  levels  of  the  \ncompany.\n ', '  In-depth  knowledge  of  labor  law  and  HR  best  practices.  ', '  Degree  in  Human  Resources  or  related  field.  '], 
            'responsibilities': ['', '  Develop  and  implement  HR  strategies  and  initiatives  aligned  with  the  overall  business  \nstrategy.\n ', '  Bridge  management  and  employee  relations  by  addressing  demands,  grievances,  or  other  \nissues.\n ', '  Manage  the  recruitment  and  selection  process.  ', '  Support  current  and  future  business  needs  through  the  development,  engagement,  \nmotivation,\n \nand\n \npreservation\n \nof\n \nhuman\n \ncapital.\n ', '  Develop  and  monitor  overall  HR  strategies,  systems,  tactics,  and  procedures  across  the  \norganization.\n ', '  Nurture  a  positive  working  environment.  ', '  Oversee  and  manage  a  performance  appraisal  system  that  drives  high  performance.  ', '  Maintain  pay  plans  and  benefits  programs.  ', '  Assess  training  needs  to  apply  and  monitor  training  programs.  ', '  Report  to  management  and  provide  decision  support  through  HR  metrics.  ', '  Ensure  legal  compliance  throughout  human  resource  management. '], 
            'custom_questions': ["What is the highest level of eduation the applicant has achieved?", "Is the applicant proficient with any languages other than English?"],
            "user_id": 1, 
            "job_id": 2}
    start_time = timeit.default_timer()
    res = run_get_gpt_results(**args)
    print(res["input_tokens"])
    print(res["output_tokens"])

    print(f"Total cost = {0.15 * (res["input_tokens"] / 1000000) + 0.6 * (res["output_tokens"] / 1000000)}")
    total_time = timeit.default_timer() - start_time
    print(total_time)
    